# Generated by Django 4.2 on 2024-01-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
